name: status
main: com.example.orestatus.OreStatusPlugin
version: 2.3.6
api-version: 1.21
commands:
  setStatus:
    description: Set player status tier
    usage: /setStatus [player] <iron|diamond|netherite|clear>
    permission: orestatus.set
  
  showStatus:
    description: Show status
    usage: /showStatus [player]
    permission: orestatus.show
  
  SetMaceDmgLimit:
    description: Set mace count
    usage: /setmacedmglimit <limit>
    permission: op

  setMaces:
    description: Set the maximum number of maces allowed on the server
    usage: /setMaces <amount>
    permission: orestatus.set
  
  allowSpears:
    description: Toggle spear features (except lunge) for a player
    usage: /allowSpears <player> <true|false>
    permission: orestatus.set

permissions:
  orestatus.set:
    default: op
  orestatus.show:
    default: true

